/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import org.terasology.math.geom.Vector3f;
import org.terasology.math.geom.Quat4f;
import org.terasology.math.geom.Matrix3f;
import org.terasology.math.geom.Matrix4f;

public class btTriangleShape extends btPolyhedralConvexShape {
	private long swigCPtr;
	
	protected btTriangleShape(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, CollisionJNI.btTriangleShape_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new btTriangleShape, normally you should not need this constructor it's intended for low-level usage. */
	public btTriangleShape(long cPtr, boolean cMemoryOwn) {
		this("btTriangleShape", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(CollisionJNI.btTriangleShape_SWIGUpcast(swigCPtr = cPtr), cMemoryOwn);
	}
	
	public static long getCPtr(btTriangleShape obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				CollisionJNI.delete_btTriangleShape(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public void setVertices1(btVector3 value) {
    CollisionJNI.btTriangleShape_vertices1_set(swigCPtr, this, btVector3.getCPtr(value), value);
  }

  public btVector3 getVertices1() {
    long cPtr = CollisionJNI.btTriangleShape_vertices1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new btVector3(cPtr, false);
  }

  public Vector3f getVertexPtr(int index) {
	return CollisionJNI.btTriangleShape_getVertexPtr__SWIG_0(swigCPtr, this, index);
}

  public btTriangleShape() {
    this(CollisionJNI.new_btTriangleShape__SWIG_0(), true);
  }

  public btTriangleShape(Vector3f p0, Vector3f p1, Vector3f p2) {
    this(CollisionJNI.new_btTriangleShape__SWIG_1(p0, p1, p2), true);
  }

  public void calcNormal(Vector3f normal) {
    CollisionJNI.btTriangleShape_calcNormal(swigCPtr, this, normal);
  }

  public void getPlaneEquation(int i, Vector3f planeNormal, Vector3f planeSupport) {
    CollisionJNI.btTriangleShape_getPlaneEquation(swigCPtr, this, i, planeNormal, planeSupport);
  }

}
