/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.dynamics;

import com.badlogic.gdx.physics.bullet.BulletBase;
import com.badlogic.gdx.physics.bullet.linearmath.*;
import com.badlogic.gdx.physics.bullet.collision.*;
import org.terasology.math.geom.Vector3f;
import org.terasology.math.geom.Quat4f;
import org.terasology.math.geom.Matrix3f;
import org.terasology.math.geom.Matrix4f;

public class btSolve2LinearConstraint extends BulletBase {
	private long swigCPtr;
	
	protected btSolve2LinearConstraint(final String className, long cPtr, boolean cMemoryOwn) {
		super(className, cPtr, cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	/** Construct a new btSolve2LinearConstraint, normally you should not need this constructor it's intended for low-level usage. */ 
	public btSolve2LinearConstraint(long cPtr, boolean cMemoryOwn) {
		this("btSolve2LinearConstraint", cPtr, cMemoryOwn);
		construct();
	}
	
	@Override
	protected void reset(long cPtr, boolean cMemoryOwn) {
		if (!destroyed)
			destroy();
		super.reset(swigCPtr = cPtr, cMemoryOwn);
	}
	
	public static long getCPtr(btSolve2LinearConstraint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	@Override
	protected void finalize() throws Throwable {
		if (!destroyed)
			destroy();
		super.finalize();
	}

  @Override protected synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				DynamicsJNI.delete_btSolve2LinearConstraint(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

  public btSolve2LinearConstraint(float tau, float damping) {
    this(DynamicsJNI.new_btSolve2LinearConstraint(tau, damping), true);
  }

  public void resolveUnilateralPairConstraint(btRigidBody body0, btRigidBody body1, Matrix3f world2A, Matrix3f world2B, Vector3f invInertiaADiag, float invMassA, Vector3f linvelA, Vector3f angvelA, Vector3f rel_posA1, Vector3f invInertiaBDiag, float invMassB, Vector3f linvelB, Vector3f angvelB, Vector3f rel_posA2, float depthA, Vector3f normalA, Vector3f rel_posB1, Vector3f rel_posB2, float depthB, Vector3f normalB, SWIGTYPE_p_float imp0, SWIGTYPE_p_float imp1) {
    DynamicsJNI.btSolve2LinearConstraint_resolveUnilateralPairConstraint(swigCPtr, this, btRigidBody.getCPtr(body0), body0, btRigidBody.getCPtr(body1), body1, world2A, world2B, invInertiaADiag, invMassA, linvelA, angvelA, rel_posA1, invInertiaBDiag, invMassB, linvelB, angvelB, rel_posA2, depthA, normalA, rel_posB1, rel_posB2, depthB, normalB, SWIGTYPE_p_float.getCPtr(imp0), SWIGTYPE_p_float.getCPtr(imp1));
  }

  public void resolveBilateralPairConstraint(btRigidBody body0, btRigidBody body1, Matrix3f world2A, Matrix3f world2B, Vector3f invInertiaADiag, float invMassA, Vector3f linvelA, Vector3f angvelA, Vector3f rel_posA1, Vector3f invInertiaBDiag, float invMassB, Vector3f linvelB, Vector3f angvelB, Vector3f rel_posA2, float depthA, Vector3f normalA, Vector3f rel_posB1, Vector3f rel_posB2, float depthB, Vector3f normalB, SWIGTYPE_p_float imp0, SWIGTYPE_p_float imp1) {
    DynamicsJNI.btSolve2LinearConstraint_resolveBilateralPairConstraint(swigCPtr, this, btRigidBody.getCPtr(body0), body0, btRigidBody.getCPtr(body1), body1, world2A, world2B, invInertiaADiag, invMassA, linvelA, angvelA, rel_posA1, invInertiaBDiag, invMassB, linvelB, angvelB, rel_posA2, depthA, normalA, rel_posB1, rel_posB2, depthB, normalB, SWIGTYPE_p_float.getCPtr(imp0), SWIGTYPE_p_float.getCPtr(imp1));
  }

}
