name: Linux amd64

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install SWIG
              run: sudo apt-get install swig mingw-w64
            - uses: actions/checkout@v3
              with:
                submodules: true
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'adopt'
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Download all artifacts
              uses: actions/download-artifact@v2
              with:
                path: .
            - name: Build
              run: ./gradlew buildNatives
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: linux-windows-amd64-artifacts
                path: |
                  build/natives/*/*.so
                  build/natives/*/*.dll
                  build/natives/*/*.dylib
