name: MacOS aarch64 (M1)

on: [push]

jobs:
    build:
        runs-on: macos-14
        steps:
            - name: Install SWIG and CMake
              run: |
                brew install swig
                brew install cmake
            - uses: actions/checkout@v3
              with:
                submodules: true
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'adopt'
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Build
              run: ./gradlew native_macosx_aarch64_clang
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: macosx-aarch64-artifacts
                path: |
                  build/natives/*/*.so
                  build/natives/*/*.dll
                  build/natives/*/*.dylib
