name: Publish Artifacts

on: 
  workflow_run:
    workflows: ["MacOS amd64", "MacOS aarch64", "Linux amd64"]
    types: [completed]
    branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:            
            - uses: actions/checkout@v3
              with:
                submodules: true
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'adopt'
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Download all artifacts
              uses: actions/download-artifact@v2
              with:
                path: .
            - name: Build Java
              run: ./gradlew build
            - name: Check Results
              run: |
                ls -l build/libs/
                ls -l build/natives/
